# Generated by Django 4.2.24 on 2025-09-17 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='HIGHLAND COMPANY LTD', max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('tin_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='TIN Number')),
                ('bank_name', models.CharField(blank=True, help_text='e.g., CRDB Bank', max_length=255, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank A/C Number')),
                ('account_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank A/C Name')),
                ('tagline', models.CharField(blank=True, help_text='e.g., Quality Solutions, Delivered.', max_length=255, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram URL')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('qr_code', models.ImageField(blank=True, editable=False, upload_to='company_qr_codes/')),
            ],
            options={
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='employee_photos/')),
                ('employee_id', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('qr_code', models.ImageField(blank=True, editable=False, upload_to='employee_qr_codes/')),
                ('issue_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('issue_date', models.DateTimeField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('client_name', models.CharField(max_length=255)),
                ('client_address', models.TextField()),
                ('client_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('other_comments', models.TextField(blank=True, null=True)),
                ('terms_of_payment', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='generator.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_card', to='generator.employee')),
            ],
        ),
    ]
