# Generated by Django 4.2.24 on 2025-09-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='TIN',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TIN'),
        ),
    ]
