# Generated by Django 4.2.24 on 2025-09-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_companyinfo_tin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True),
        ),
    ]
